name: build images

on:
  push:
    branches:
      - master


jobs:
  build_images:
    name: build images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build app
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: janvt/roks:app
          file: Dockerfile.prod
      - name: build web
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: janvt/roks:web
          file: Dockerfile.prod.nginx
          build-args: |
            ASSET_IMAGE=janvt/roks:app
